/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import UserInterface.WorkAreas.AdminRole.ManageUserAccountsJPanel;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;
import UserInterface.WorkAreas.AdminRole.PersonRegistrationPanel;
import UserInterface.WorkAreas.AdminRole.AdminProfilePanel;
import javax.swing.JPanel;
import Business.Profiles.EmployeeProfile;

/**
 *
 * @author kal
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;

    /**
     * Creates new form UnitRiskWorkArea
     */
EmployeeProfile adminProfile;
    public AdminRoleWorkAreaJPanel(Business b, EmployeeProfile ep, JPanel clp) 
    {
    business = b;
    adminProfile = ep;
    this.CardSequencePanel = clp;
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btnAdminUserAcc = new javax.swing.JButton();
        btnManageFaculty = new javax.swing.JButton();
        btnRegisterPerson = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnManageStudents = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();
        btnManageRegistrar = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnAdminUserAcc.setBackground(new java.awt.Color(102, 153, 255));
        btnAdminUserAcc.setFont(getFont());
        btnAdminUserAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUserAcc.setText("Administer User Accounts");
        btnAdminUserAcc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdminUserAcc.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAdminUserAcc.setMinimumSize(new java.awt.Dimension(20, 23));
        btnAdminUserAcc.setPreferredSize(new java.awt.Dimension(240, 30));
        btnAdminUserAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminUserAccIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageFaculty.setBackground(new java.awt.Color(102, 153, 255));
        btnManageFaculty.setFont(getFont());
        btnManageFaculty.setForeground(new java.awt.Color(255, 255, 255));
        btnManageFaculty.setText("Manage Faculty");
        btnManageFaculty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageFaculty.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageFaculty.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageFaculty.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFacultyActionPerformed(evt);
            }
        });

        btnRegisterPerson.setBackground(new java.awt.Color(102, 153, 255));
        btnRegisterPerson.setFont(getFont());
        btnRegisterPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterPerson.setText("Register  Persons (HR)");
        btnRegisterPerson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegisterPerson.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegisterPerson.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRegisterPerson.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRegisterPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPersonActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnProfile.setFont(getFont());
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("My Profile");
        btnProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileIdentifyEventsActionPerformed(evt);
            }
        });

        btnManageStudents.setBackground(new java.awt.Color(102, 153, 255));
        btnManageStudents.setFont(getFont());
        btnManageStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStudents.setText("Manage Students");
        btnManageStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudents.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageStudents.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageStudents.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentsActionPerformed(evt);
            }
        });

        btnAnalytics.setBackground(new java.awt.Color(102, 153, 255));
        btnAnalytics.setFont(getFont());
        btnAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        btnAnalytics.setText("Analytics");
        btnAnalytics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAnalytics.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAnalytics.setMinimumSize(new java.awt.Dimension(20, 23));
        btnAnalytics.setPreferredSize(new java.awt.Dimension(240, 30));
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageRegistrar.setBackground(new java.awt.Color(102, 153, 255));
        btnManageRegistrar.setFont(getFont());
        btnManageRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnManageRegistrar.setText("Manage Registrar");
        btnManageRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageRegistrar.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageRegistrar.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageRegistrar.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminUserAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnManageRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void btnAdminUserAccIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

       ManageUserAccountsJPanel panel = new ManageUserAccountsJPanel(business, CardSequencePanel);
    CardSequencePanel.add("ManageUserAccounts", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }

    private void btnRegisterPersonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        PersonRegistrationPanel panel = new PersonRegistrationPanel(business, CardSequencePanel);
    CardSequencePanel.add("PersonRegistration", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }

    private void btnManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ManageStudentsPanel panel = new ManageStudentsPanel(business, CardSequencePanel);
    CardSequencePanel.add("ManageStudents", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }

    private void btnProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {
  AdminProfilePanel panel = new AdminProfilePanel(business, adminProfile, CardSequencePanel);
    CardSequencePanel.add("AdminProfile", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);    }

    private void btnManageFacultyActionPerformed(java.awt.event.ActionEvent evt) {
ManageFacultyPanel panel = new ManageFacultyPanel(business, CardSequencePanel);
    CardSequencePanel.add("ManageFaculty", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);    }

    private void btnAnalyticsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {
AnalyticsDashboardPanel panel = new AnalyticsDashboardPanel(business, CardSequencePanel);
    CardSequencePanel.add("Analytics", panel);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);        // TODO add your handling code here:
    }

    private void btnManageRegistrarActionPerformed(java.awt.event.ActionEvent evt) {
        ManageRegistrarPanel panel = new ManageRegistrarPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageRegistrar", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnAdminUserAcc;
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnManageFaculty;
    private javax.swing.JButton btnManageStudents;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRegisterPerson;
    private javax.swing.JButton btnManageRegistrar;
    // End of variables declaration

}